run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - revive
    - gosec
    - gocyclo
    - depguard
    - dupl
    - funlen
    - gocognit
    - nestif
    - maintidx
    - errname
    - unparam
    - bodyclose
    - forcetypeassert

linters-settings:
  depguard:
    rules:
      Main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "use github.com/bborbe/errors instead"
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 30
  nestif:
    min-complexity: 5
  maintidx:
    threshold: 20

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019" # allow deprecated in specific cases
    - linters:
        - revive
      path: "_test\\.go$"
      text: "dot-imports"
    - linters:
        - revive
      text: "unused-parameter"
    - linters:
        - revive
      text: "stutters"
    - linters:
        - funlen
      path: "_test\\.go$"
    - linters:
        - gocognit
      path: "_test\\.go$"
